name: AimCvent-Boat
version: '${project.version}'
main: me.aimcventboat.main.Main
api-version: 1.18
authors: [ LoliChann ]
description: Boat run AimCvent
commands:
  test:
    description: test
    permission: test.use
  boat_start:
    description: test
    permission: boat.launcher.start
  boat_end:
    description: test
    permission: boat.launcher.start
  set_start:
    description: test
    permission: boat.launcher.set_start
  pnj_summon:
    description: test
    permission: test
  checkpoint_pass:
    description: test
    permission : test
  run_add:
    description: test
    permission: test
  competition:
    description: test
    permission: test
  compet_join:
    description: test
  compet_start:
    description: test
  compet_end:
    description: test
  hologram:
    description: test
  hologram_rm:
    description: test
  run_rm:
    description: test
  hologram_menu:
    description: test